[project]
name = "nuanced-mcp"
version = "0.1.0"
description = "MCP server expose nuanced.dev functionality"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.3.0",
    "nuanced>=0.1.3",
]
